In [4]:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

nnfs.init()

X, y = spiral_data(100, 3)  

In [5]:
classBatchInput =[ [1,2,3,2.5], 
                  [2.0,5.0,-1.0,2.0], 
                   [-1.5,2.7,3.3,-0.8]] 

In [31]:
np.random.seed(0)

layer1 = Layer_Dense(4,5)
layer1.forward(np.array(classBatchInput))
print(layer1.weights)

self.weights shape :  [4, 5]
self.bias shape :  [1, 5]
Input shape :  [3, 4]
[[ 0.17640524  0.04001572  0.0978738   0.22408931  0.1867558 ]
 [-0.09772779  0.09500884 -0.01513572 -0.01032189  0.04105985]
 [ 0.01440436  0.14542735  0.07610377  0.0121675   0.04438632]
 [ 0.03336744  0.14940791 -0.02051583  0.03130677 -0.08540957]]


In [32]:
np.random.seed(0)
layer1umer = DenseLayer_umer(4,5)
layer1umer.forward(classBatchInput)
print(layer1umer.weightsSet)

self.weights shape :  [4, 5]
self.bias shape :  [5]
Input shape :  [3, 4]
[[0.17640524, 0.04001572, 0.0978738, 0.22408931, 0.1867558], [-0.09772779, 0.09500884, -0.01513572, -0.01032189, 0.04105985], [0.01440436, 0.14542735, 0.07610377, 0.0121675, 0.04438632], [0.03336744, 0.14940791, -0.02051583, 0.03130677, -0.08540957]]


In [29]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        
        self.biases = np.zeros((1, n_neurons))
        print("self.weights shape : ", getDimension(self.weights))
        print("self.bias shape : ", getDimension(self.biases))
    def forward(self, inputs):
        print("Input shape : ", getDimension(inputs))
        self.output = np.dot(inputs, self.weights) + self.biases


In [11]:
def getDimension(a):
    if type(a) == list or type(a) == np.ndarray:
        return [len(a)] + getDimension(a[0])
    else:
        return []


In [30]:
class DenseLayer_umer:
    
    def __init__(self,n_inputs,n_neurons):
#         self.weightsSet = 0.10 * np.random.randn(n_neurons,n_inputs)
        self.weightsSet = [[ 0.17640524 , 0.04001572 , 0.0978738,   0.22408931 , 0.1867558 ],
                         [-0.09772779 , 0.09500884, -0.01513572 ,-0.01032189,  0.04105985],
                         [ 0.01440436 , 0.14542735,  0.07610377,  0.0121675 ,  0.04438632],
                         [ 0.03336744 , 0.14940791, -0.02051583,  0.03130677 ,-0.08540957]]
        self.bias = np.zeros((n_neurons,)) 

        print("self.weights shape : ", getDimension(self.weightsSet))
        print("self.bias shape : ", getDimension(self.bias))
        
    def forward(self,batchInput):
        self.batchInput = batchInput
        print("Input shape : ", getDimension(batchInput))
        self.output = self.ProcessBatchInput()
#         self.output = np.dot(batchInput,self.weightsSet.T)
        
    def ProcessBatchInput(self):
        output = []
        inputNumber=0
        for input in self.batchInput:
            output.append(self.CalculateOutputForLayer(input))
            inputNumber+=1
        return output
    
    '''
    @params
    input =  list of numbers
    weights = list of lists.
    bias  =  list of numbers
    @output:
    output = list of numbers.representing the output for one neuron from the whole previous layer
    '''

    def CalculateOutputForLayer(self,input):
        output = []
        numConnections = len(self.weightsSet)       #because weights outer layer tells us how many neurons are there in next level
        for index in range(numConnections):
            output.append(self.CalculateOutputForOneNeuron(input,self.weightsSet[index],self.bias[index]))
        return output
    
    
    '''
    @params
    input = list of numbers
    weights = list.
    bias = numbers
    @output:
    output = number. representing the output for one neuron from one neuron
    '''

    def CalculateOutputForOneNeuron(self,input,weights,bias):
        output = self.dotProduct(input,weights)
        output += bias
        return round(output,3)
    
    
    '''
    @params
    firstList = a lsit
    secondList = a lsit
    @output:
    outputList = a number
    '''

    def dotProduct(self,firstList,secondList):
        outputList = 0
        for i,j in zip(firstList,secondList):
            outputList += (i*j)
        return outputList